export default [
  { "value": "BDO", "description": "Bottlenose dolphin", "scientific": "Tursiops truncatus" },
  { "value": "CDD", "description": "Common dolphin", "scientific": "Delphinus delphis" },
  { "value": "DDO", "description": "Dusky dolphin", "scientific": "Lagenorhynchus obscurus" },
  { "value": "EPH", "description": "Elephant seal", "scientific": "" },
  { "value": "FIW", "description": "Fin whale", "scientific": "" },
  { "value": "HDO", "description": "Hector's dolphin", "scientific": "" },
  { "value": "HBW", "description": "Humpback whale", "scientific": "" },
  { "value": "LEO", "description": "Leopard seal", "scientific": "" },
  { "value": "HDM", "description": "Maui's dolphin", "scientific": "" },
  { "value": "MIW", "description": "Minke whale", "scientific": "" },
  { "value": "FUR", "description": "New Zealand fur seal", "scientific": "" },
  { "value": "HSL", "description": "New Zealand sea lion", "scientific": "" },
  { "value": "ORC", "description": "Orca", "scientific": "" },
  { "value": "PIW", "description": "Pilot whale", "scientific": "" },
  { "value": "SEW", "description": "Sei whale", "scientific": "" },
  { "value": "SRW", "description": "Southern right whale", "scientific": "" },
  { "value": "PHD", "description": "Spectacled porpoise", "scientific": "" },
  { "value": "WHT", "description": "Dolphins and toothed whales", "scientific": "" },
  { "value": "WHB", "description": "Baleen whales", "scientific": "" },
  { "value": "SEA", "description": "Seals and sealions", "scientific": "" },
];
