export default [
  { "value": "XAL", "description": "Albatrosses (unidentified)", "scientific": "" },
  { "value": "XXP", "description": "Petrels, prions and shearwaters", "scientific": "" },
  { "value": "XLA", "description": "Gulls and terns", "scientific": "" },
  { "value": "XHG", "description": "Shags", "scientific": "" },
  { "value": "XSU", "description": "Boobies and gannets", "scientific": "" },
  { "value": "XPG", "description": "Penguins", "scientific": "" },
  { "value": "XAF", "description": "Antarctic fulmar", "scientific": "Fulmarus glacialoides" },
  { "value": "XAP", "description": "Antarctic petrel", "scientific": "Thalassoica antarctica" },
  { "value": "XPR", "description": "Antarctic prion", "scientific": "Pachyptila desolata" },
  { "value": "XAG", "description": "Antipodean and Gibson's albatross", "scientific": "Diomedea antipodensis" },
  { "value": "XGT", "description": "Australasian gannet", "scientific": "Morus serrator" },
  { "value": "XBP", "description": "Black petrel", "scientific": "Procellaria parkinsoni" },
  { "value": "XBG", "description": "Black-backed gull", "scientific": "Larus dominicanus" },
  { "value": "XFT", "description": "Black-bellied storm petrel", "scientific": "Fregetta tropica" },
  { "value": "XPV", "description": "Broad-billed prion", "scientific": "Pachyptila vittata" },
  { "value": "XPB", "description": "Buller's and Pacific albatross", "scientific": "Thalassarche bulleri" },
  { "value": "XBS", "description": "Buller's shearwater", "scientific": "Puffinus bulleri" },
  { "value": "XCM", "description": "Campbell albatross", "scientific": "Thallassarche impavida" },
  { "value": "XCC", "description": "Cape petrel", "scientific": "Daption capense" },
  { "value": "XCI", "description": "Chatham Island albatross", "scientific": "Thalassarche eremita" },
  { "value": "XDP", "description": "Common diving petrel", "scientific": "Pelecanoides urinatrix" },
  { "value": "XFP", "description": "Fairy prion", "scientific": "Pachyptila turtur" },
  { "value": "XFS", "description": "Flesh-footed shearwater", "scientific": "Puffinus carneipes" },
  { "value": "XFL", "description": "Fluttering shearwater", "scientific": "Puffinus gavia" },
  { "value": "XGF", "description": "Great-winged petrel", "scientific": "Pterodroma macroptera" },
  { "value": "XGP", "description": "Grey petrel", "scientific": "Procellaria cinerea" },
  { "value": "XGB", "description": "Grey-backed storm petrel", "scientific": "Garrodia nereis" },
  { "value": "XGM", "description": "Grey-headed albatross", "scientific": "Thalassarche chrysostoma" },
  { "value": "XLM", "description": "Light-mantled sooty albatross", "scientific": "Phoebetria palpebrata" },
  { "value": "XLB", "description": "Little blue penguin", "scientific": "Eudyptula minor" },
  { "value": "XMB", "description": "Masked booby", "scientific": "Sula dactylatra fullageri" },
  { "value": "XNP", "description": "Northern giant petrel", "scientific": "Macronectes halli" },
  { "value": "XNR", "description": "Northern royal albatross", "scientific": "Diomedea sanfordi" },
  { "value": "XPS", "description": "Pied shag", "scientific": "Phalacrocorax varius" },
  { "value": "XRB", "description": "Red-billed gull", "scientific": "Larus novaehollandiae scopulinus" },
  { "value": "XSA", "description": "Salvin's albatross", "scientific": "Thalassarche salvini" },
  { "value": "XTS", "description": "Short-tailed shearwater", "scientific": "Puffinus tenuirostris" },
  { "value": "XSY", "description": "Shy albatross", "scientific": "Thalassarche cauta" },
  { "value": "XSH", "description": "Sooty shearwater", "scientific": "Puffinus griseus" },
  { "value": "XSM", "description": "Southern black-browed albatross", "scientific": "Thalassarche melanophris" },
  { "value": "XSP", "description": "Southern giant petrel", "scientific": "Macronectes giganteus" },
  { "value": "XRA", "description": "Southern royal albatross", "scientific": "Diomedea epomophora" },
  { "value": "XPP", "description": "Spotted shag", "scientific": "Phalacrocorax punctatus" },
  { "value": "XAS", "description": "Wandering albatross", "scientific": "Diomedea exulans" },
  { "value": "XWP", "description": "Westland petrel", "scientific": "Procellaria westlandica" },
  { "value": "XWB", "description": "White-bellied storm petrel", "scientific": "Fregetta grallaria grallaria" },
  { "value": "XWM", "description": "White-capped albatross", "scientific": "Thalassarche steadi" },
  { "value": "XWC", "description": "White-chinned petrel", "scientific": "Procellaria aequinoctialis" },
  { "value": "XWF", "description": "White-faced storm petrel", "scientific": "Pelagodroma marina" },
  { "value": "XWH", "description": "White-headed petrel", "scientific": "Pterodroma lessonii" },
  { "value": "XYP", "description": "Yellow-eyed penguin", "scientific": "Megadytes antipodes" },
];
