export default [
  {"value": "SNX", "description": "Small Snapper"},
  {"value":"CAC","description":"Cancer Crab"},
  {"value":"CRB","description":"Crab"},
  {"value":"PAD","description":"Paddle Crab"},
  {"value":"SPI","description":"Spider Crab"},
  {"value":"PRA","description":"Prawn"},
  {"value":"SCI","description":"Scampi"},
  {"value":"MUN","description":"Munidagregaria"},
  {"value":"CRA","description":"Rock Lobster"},
  {"value":"PHC","description":"Packhorse Rock Lobster"},
  {"value":"PRK","description":"Prawn Killer"},
  {"value":"SLO","description":"Spanish Lobster"},
  {"value":"SCC","description":"Sea Cucumber"},
  {"value":"SFI","description":"Starfish"},
  {"value":"SUR","description":"Kina"},
  {"value":"BEM","description":"Blue Marlin"},
  {"value":"BKM","description":"Black Marlin"},
  {"value":"SAI","description":"Sailfish"},
  {"value":"SSF","description":"Shortbill Spearfish"},
  {"value":"STM","description":"Striped Marlin"},
  {"value":"SWO","description":"Broadbill Swordfish"},
  {"value":"CHI","description":"Chimaerasp."},
  {"value":"GSH","description":"Ghost Shark"},
  {"value":"GSP","description":"Pale Ghost Shark"},
  {"value":"LCH","description":"Long-nosed Chimaera"},
  {"value":"BFL","description":"Black Flounder"},
  {"value":"BRI","description":"Brill"},
  {"value":"ESO","description":"N.Z.Sole"},
  {"value":"FLA","description":"Flats"},
  {"value":"GFL","description":"Greenback Flounder"},
  {"value":"LSO","description":"Lemon Sole"},
  {"value":"SFL","description":"Sand Flounder"},
  {"value":"TUR","description":"Turbot"},
  {"value":"WIT","description":"Witch"},
  {"value":"YBF","description":"Yellow-belly Flounder"},
  {"value":"AGR","description":"Ribbonfish"},
  {"value":"ANC","description":"Anchovy"},
  {"value":"ATO","description":"Antarctic Toothfish"},
  {"value":"BAR","description":"Barracouta"},
  {"value":"BAS","description":"Bass Groper"},
  {"value":"BBE","description":"Banded Bellowsfish"},
  {"value":"BCA","description":"Barracudina"},
  {"value":"BCD","description":"Black Cod"},
  {"value":"BCO","description":"Blue Cod"},
  {"value":"BCR","description":"Blue Cusk Eel"},
  {"value":"BEL","description":"Bellowsfish"},
  {"value":"BGZ","description":"Banded Giant Stargazer"},
  {"value":"BMA","description":"Blue Maomao"},
  {"value":"BNS","description":"Bluenose"},
  {"value":"BOA","description":"Sowfish"},
  {"value":"BOE","description":"Black Oreo"},
  {"value":"BOX","description":"Boxfish"},
  {"value":"BPF","description":"Banded Wrasse"},
  {"value":"BRC","description":"Northern Bastard Cod"},
  {"value":"BRZ","description":"Brown Stargazer"},
  {"value":"BSP","description":"Big-scale Pomfret"},
  {"value":"BUT","description":"Butterfish"},
  {"value":"BYX","description":"Alfonsino & Long-finned Beryx"},
  {"value":"CAN","description":"Brown Brotula"},
  {"value":"CDL","description":"Cardinal Fish"},
  {"value":"CMO","description":"Copper Moki"},
  {"value":"DEA","description":"Dealfish"},
  {"value":"DIS","description":"Discfish"},
  {"value":"DOF","description":"Dolphinfish"},
  {"value":"DSS","description":"Deepsea Smelt"},
  {"value":"ELE","description":"Elephant Fish"},
  {"value":"EMP","description":"Emperor"},
  {"value":"EPD","description":"White Cardinalfish"},
  {"value":"EPL","description":"Bigeye Cardinalfish"},
  {"value":"EPR","description":"Robust Cardinalfish"},
  {"value":"FHD","description":"Deepsea Flathead"},
  {"value":"FLY","description":"Flying Fish"},
  {"value":"FRO","description":"Frostfish"},
  {"value":"GAR","description":"Garfish"},
  {"value":"GMU","description":"Grey Mullet"},
  {"value":"GSE","description":"Snake Mackerel"},
  {"value":"GTR","description":"Marblefish"},
  {"value":"GUR","description":"Gurnard"},
  {"value":"HAG","description":"Hagfish"},
  {"value":"HAK","description":"Hake"},
  {"value":"HAP","description":"Hapuku"},
  {"value":"HJO","description":"Johnsons Cod"},
  {"value":"HOK","description":"Hoki"},
  {"value":"HPB","description":"Hapuku&Bass"},
  {"value":"ICX","description":"Icefishes"},
  {"value":"JDO","description":"John Dory"},
  {"value":"JGU","description":"Japanese Gurnard"},
  {"value":"JMA","description":"Jack Mackerel"},
  {"value":"KAH","description":"Kahawai"},
  {"value":"KEL","description":"Kelpfish"},
  {"value":"KIN","description":"Kingfish"},
  {"value":"KOH","description":"Koheru"},
  {"value":"KTA","description":"King Tarakihi"},
  {"value":"LAN","description":"Lantern Fish"},
  {"value":"LDO","description":"Lookdown Dory"},
  {"value":"LEA","description":"Leatherjacket"},
  {"value":"LEG","description":"Giant Lepidion"},
  {"value":"LEP","description":"Escolar"},
  {"value":"LFB","description":"Longfinned Boarfish"},
  {"value":"LIN","description":"Ling"},
  {"value":"MDO","description":"Mirror Dory"},
  {"value":"MOK","description":"Moki"},
  {"value":"MOO","description":"Moonfish"},
  {"value":"MRL","description":"Moray Cods"},
  {"value":"NOT","description":"Antarctic Rock Cods"},
  {"value":"OAR","description":"Oarfish"},
  {"value":"OEO","description":"Oreos"},
  {"value":"OFH","description":"Oilfish"},
  {"value":"OPE","description":"Orange Perch"},
  {"value":"ORH","description":"Orange Roughy"},
  {"value":"PAR","description":"Parore"},
  {"value":"PGR","description":"Plunderfish"},
  {"value":"PIG","description":"Pigfish"},
  {"value":"PIL","description":"Pilchard"},
  {"value":"PIP","description":"Pipefish"},
  {"value":"PMA","description":"Pink Maomao"},
  {"value":"POP","description":"Porcupine Fish"},
  {"value":"POR","description":"Porae"},
  {"value":"PTO","description":"Patagonian Toothfish"},
  {"value":"RAG","description":"Ragfish"},
  {"value":"RBM","description":"Rays Bream"},
  {"value":"RBT","description":"Redbait"},
  {"value":"RBY","description":"Ruby Fish"},
  {"value":"RCO","description":"Red Cod"},
  {"value":"RDO","description":"Rosy Dory"},
  {"value":"RHY","description":"Common Roughy"},
  {"value":"RIB","description":"Ribaldo"},
  {"value":"RMO","description":"Red Moki"},
  {"value":"ROC","description":"Rock Cod"},
  {"value":"RPE","description":"Red Perch"},
  {"value":"RRC","description":"Red Scorpion Fish"},
  {"value":"RSN","description":"Red Snapper"},
  {"value":"RUD","description":"Rudderfish"},
  {"value":"SAM","description":"Quinnat Salmon"},
  {"value":"SAU","description":"Saury"},
  {"value":"SBO","description":"Southern Boarfish"},
  {"value":"SBW","description":"Southern Blue Whiting"},
  {"value":"SCG","description":"Scaly Gurnard"},
  {"value":"SDO","description":"Silver Dory"},
  {"value":"SEM","description":"Small Eye Moray Cod"},
  {"value":"SFN","description":"Spinyfin"},
  {"value":"SKI","description":"Gemfish"},
  {"value":"SLK","description":"Slickhead"},
  {"value":"SMC","description":"Small-headed Cod"},
  {"value":"SNA","description":"Snapper"},
  {"value":"SOR","description":"Spiky Oreo"},
  {"value":"SPE","description":"Sea Perch"},
  {"value":"SPF","description":"Scarlet Wrasse"},
  {"value":"SPP","description":"Splendid Perch"},
  {"value":"SPR","description":"Sprats"},
  {"value":"SPZ","description":"Spotted Stargazer"},
  {"value":"SSI","description":"Silverside"},
  {"value":"SSO","description":"Smooth Oreo"},
  {"value":"STA","description":"Giant Stargazer"},
  {"value":"SUN","description":"Sunfish"},
  {"value":"SWA","description":"Silver Warehou"},
  {"value":"TAR","description":"Tarakihi"},
  {"value":"TOA","description":"Toadfish"},
  {"value":"TRE","description":"Trevally"},
  {"value":"TRS","description":"Capescorpionfish"},
  {"value":"TRU","description":"Trumpeter"},
  {"value":"VCO","description":"Violet Cod"},
  {"value":"WAR","description":"Common Warehou"},
  {"value":"WOE","description":"Warty Oreo"},
  {"value":"WSE","description":"Wrasses"},
  {"value":"WWA","description":"White Warehou"},
  {"value":"YEM","description":"Yellow-eyed Mullet"},
  {"value":"COL","description":"Olivers Rattail"},
  {"value":"JAV","description":"Javelin Fish"},
  {"value":"MCA","description":"Ridge Scaled Rattail"},
  {"value":"RAT","description":"Rattails"},
  {"value":"WGR","description":"Macrouruswhitsoni"},
  {"value":"WHR","description":"White Rattail"},
  {"value":"WHX","description":"Unicorn Rattail"},
  {"value":"BEE","description":"Basketwork Eel"},
  {"value":"CON","description":"Conger Eel"},
  {"value":"DWE","description":"Deepwater Eel"},
  {"value":"EEL","description":"Eels"},
  {"value":"MOR","description":"Moray Eel"},
  {"value":"SBK","description":"Spineback"},
  {"value":"SCO","description":"Swollenhead Conger"},
  {"value":"BEA","description":"Eatons Skate"},
  {"value":"BRA","description":"Short-tailed Black Ray"},
  {"value":"DSK","description":"Deepwater Spiny Skate"},
  {"value":"EGR","description":"Eagle Ray"},
  {"value":"ERA","description":"Electric Ray"},
  {"value":"RSK","description":"Rough Skate"},
  {"value":"SKA","description":"Skate"},
  {"value":"SRR","description":"Amblyrajageorgiana"},
  {"value":"SSK","description":"Smooth Skate"},
  {"value":"STR","description":"Stingray"},
  {"value":"WRA","description":"Whiptail Ray"},
  {"value":"BSH","description":"Seal Shark"},
  {"value":"BSK","description":"Basking Shark"},
  {"value":"BWH","description":"Bronze Whaler Shark"},
  {"value":"BWS","description":"Blue Shark"},
  {"value":"CAR","description":"Carpet Shark"},
  {"value":"CSQ","description":"Leafscalegulpershark"},
  {"value":"CYO","description":"Smooth Skin Dogfish"},
  {"value":"CYP","description":"Longnosedvelvetdogfish"},
  {"value":"DWD","description":"Deepwater Dogfish"},
  {"value":"ECO","description":"Prickly Shark"},
  {"value":"ETB","description":"Baxters Lantern Dogfish"},
  {"value":"ETL","description":"Lucifer Dogfish"},
  {"value":"HEP","description":"Sharpsnouted Sevengill Shark"},
  {"value":"HHS","description":"Hammerhead Shark"},
  {"value":"MAK","description":"Mako Shark"},
  {"value":"NSD","description":"Northern Spiny Dogfish"},
  {"value":"OSD","description":"Other Sharks And Dogs"},
  {"value":"PDG","description":"Prickly Dogfish"},
  {"value":"POS","description":"Porbeagle Shark"},
  {"value":"SCH","description":"School Shark"},
  {"value":"SCM","description":"Roughskin Dogfish"},
  {"value":"SEV","description":"Broadsnouted Sevengill Shark"},
  {"value":"SND","description":"Shovelnose Spiny Dogfish"},
  {"value":"SPD","description":"Spiny Dogfish"},
  {"value":"SPO","description":"Rig"},
  {"value":"Rig","description":"Musteluslenticulatus"},
  {"value":"SSH","description":"Slender Smooth-hound"},
  {"value":"THR","description":"Thresher Shark"},
  {"value":"ALB","description":"Albacore Tuna"},
  {"value":"BIG","description":"Bigeye Tuna"},
  {"value":"BTU","description":"Butterfly Tuna"},
  {"value":"EMA","description":"Blue Mackerel"},
  {"value":"NTU","description":"Northern Bluefin Tuna"},
  {"value":"SKJ","description":"Skipjack Tuna"},
  {"value":"STN","description":"Southern Bluefin Tuna"},
  {"value":"STU","description":"Slender Tuna"},
  {"value":"TOR","description":"Pacific Bluefin Tuna"},
  {"value":"WAH","description":"Wahoo"},
  {"value":"YFN","description":"Yellowfin Tuna"},
  {"value":"BYA","description":"Frilled Venus Shell"},
  {"value":"COC","description":"Cockle"},
  {"value":"DAN","description":"Ringed Dosinia"},
  {"value":"DSU","description":"Fine Dosinia"},
  {"value":"HOR","description":"Horse Mussel"},
  {"value":"MDI","description":"Large Trough Shell"},
  {"value":"MMI","description":"Trough Shell"},
  {"value":"MSG","description":"Green-lipped Mussel"},
  {"value":"MSP","description":"Green Mussel Spat"},
  {"value":"MUS","description":"Mussels"},
  {"value":"OYS","description":"Oysters Dredge"},
  {"value":"OYU","description":"Oysters Dredge"},
  {"value":"PDO","description":"Deepwater Tuata"},
  {"value":"POY","description":"Oysters Pacific"},
  {"value":"PPI","description":"Pipi"},
  {"value":"QSC","description":"Queen Scallop"},
  {"value":"SAE","description":"Triangle Shell"},
  {"value":"SCA","description":"Scallop"},
  {"value":"TUA","description":"Tuatua"},
  {"value":"OCT","description":"Octopus"},
  {"value":"BSQ","description":"Broad Squid"},
  {"value":"GSQ","description":"Giant Squid"},
  {"value":"SQU","description":"Arrow Squid"},
  {"value":"SQX","description":"Squid"},
  {"value":"WSQ","description":"Warty Squid"},
  {"value":"CTU","description":"Cooks Turban Shell"},
  {"value":"LIM","description":"Limpets"},
  {"value":"PAU","description":"Black Paua & Yellowfoot Paua"},
  {"value":"WHE","description":"Whelks"},
  {"value":"COE","description":"Coelenterata"},
  {"value":"ONG","description":"Sponges"},
  {"value":"SAL","description":"Salps"},
  {"value":"SLG","description":"Sea Slug"},
  {"value":"GRA","description":"Gracilaria Weed"},
  {"value":"KBB","description":"Bladder Kelp"},
  {"value":"KBL","description":"Kelp Bull"},
  {"value":"LES","description":"Lessonia"},
  {"value":"PTE","description":"Pterocladia"}
];
