export default [
  {"value": "GRE", "description": "Greenamount", "species": []},
  {"value": "DRE", "description": "Dressed", "species": []},
  {"value": "FIL", "description": "Fillets skin on", "species": []},
  {"value": "SKF", "description": "Fillets skin off", "species": []},
  {"value": "FIN", "description": "Fins", "species": []},
  {"value": "MEA", "description": "Fish meal", "species": []},
  {"value": "GUT", "description": "Gutted", "species": []},
  {"value": "HGU", "description": "Headed and gutted", "species": []},
  {"value": "LIV", "description": "Livers", "species": []},
  {"value": "SUR", "description": "Surimi / Fish paste", "species": []},
  {"value": "GGT", "description": "Gilled and gutted tail off", "species": ["ALB", "BIG", "STN", "TOR", "YFN"]},
  {"value": "GGO", "description": "Gilled and gutted tail on", "species": ["ALB", "BIG", "STN", "TOR", "YFN"]},
  {"value": "FID", "description": "Fins dried", "species": ["BWS", "MAK", "POS"]},
  {"value": "FIW", "description": "Fins wet", "species": ["BWS", "MAK", "POS"]},
  {"value": "RLT", "description": "Rock lobster tail", "species": ["CRA", "PHC", "SCI"]},
  {"value": "DFT", "description": "De-fat fillets", "species": ["HOK"]},
  {"value": "HGT", "description": "Headed, gutted and tailed", "species": ["HOK", "LIN"]},
  {"value": "MGU", "description": "Mince, headed and gutted", "species": ["HOK"]},
  {"value": "MKF", "description": "Mince, skin off fillets", "species": ["HOK", "SBW"]},
  {"value": "TRF", "description": "Skin on trimmed fillets", "species": ["HOK", "LIN"]},
  {"value": "TSK", "description": "Skin off trimmed fillets", "species": ["HOK", "LIN"]},
  {"value": "UTF", "description": "Skin on untrimmed fillets", "species": ["HOK", "LIN"]},
  {"value": "USK", "description": "Skin off untrimmed fillets", "species": ["LIN"]},
  {"value": "SHU", "description": "Shucked / Shelled", "species": ["PAU", "SCA"]},
  {"value": "WRS", "description": "Wings", "species": ["RSK", "SSK"]},
  {"value": "TEN", "description": "Tentacles", "species": ["SQU"]},
  {"value": "DSC", "description": "Dressed-straight cut", "species": ["STA"]},
  {"value": "DVC", "description": "Dressed-v cut", "species": ["STA"]},
  {"value": "HGF", "description": "Headed, gutted and finned", "species": ["SWO"]},
];
