export default [
  { "value": "Tarakohe", "description": "Golden Bay" },
  { "value": "Tutukaka", "description": "Northland" },
  { "value": "Whangerei Harbour", "description": "Northland" },
  { "value": "Auckland Viaduct", "description": "Auckland" },
  { "value": "Onehunga Wharf", "description": "Auckland" },
  { "value": "Port Tauranga", "description": "Bay of Plenty" },
  { "value": "Port Taranaki", "description": "Taranaki" },
  { "value": "Napier", "description": "Hawkes Bay" },
  { "value": "Gisbourne", "description": "Hawkes Bay" },
  { "value": "Wellington Harbour", "description": "Wellington" },
  { "value": "Port Motueka", "description": "Nelson" },
  { "value": "Port Nelson Wharf", "description": "Nelson" },
  { "value": "Westport", "description": "West Coast" },
  { "value": "Greymouth", "description": "West Coast" },
  { "value": "Lyttleton", "description": "Canterbury" },
  { "value": "Akaroa", "description": "Canterbury" },
  { "value": "Timaru", "description": "Canterbury" },
  { "value": "Port Chalmers", "description": "Otago" },
  { "value": "Carey's Bay", "description": "Otago" },
  { "value": "Dunedin Wharf", "description": "Otago" },
  { "value": "Bluff", "description": "Southland" },
];
