
import Validator from '../utils/Validator';
const combined = Validator.combined;
const valid = Validator.valid;

const TCERModel = [
  {
    id: 'fishingMethod',
    default: 'BT',
    repeating: true,
    realm: { type: 'string' },
  },
  /*{
    label: 'Bottom Depth',
    id: 'bottomDepth',
    valid: valid.greaterThanZero,
    type: 'number',
    unit: 'm',
    default: 0,
    display: { type: 'combined', siblings: ['groundropeDepth'] },
    realm: { type: 'int', optional: true },
  },*/
  {
    label: 'Number of People',
    id: 'numberOfNets',
    valid: valid.greaterThanZero,
    type: 'number',
    default: 1,
    repeating: true,
    display: { type: 'single' },
    realm: { type: 'int' },
  },
  /*{
    label: 'Estimated Total Bag Size',
    id: 'estimatedCatchKg',
    valid: valid.anyValue,
    type: 'number',
    default: 0,
    repeating: true,
    displayStage: 'Haul',
    unit: 'kg',
    display: { type: 'single' },
    realm: { type: 'int', optional: true },
  },
  {
    label: 'Vessel Pair Number',
    id: 'vesselPairNumber',
    valid: valid.anyValue,
    type: 'number',
    default: null,
    repeating: true,
    display: { type: 'single' },
    realm: { type: 'int', optional: true },
  },
  {
    label: 'Minimum Mesh Size',
    id: 'minMeshSizeMm',
    valid: valid.greaterThanZero,
    type: 'float',
    default: 0,
    unit: 'mm',
    repeating: true,
    display: { type: 'single' },
    realm: { type: 'float' },
  },
  {
    label: 'Start of Haul Location',
    id: 'NetLeaveDepthLocation',
    valid: valid.locationValid,
    type: 'location',
    default: null,
    copyFrom: 'locationEnd',
    displayStage: 'Haul',
    display: { type: 'single' },
    optionalRender: true,
    realm: { type: 'string', optional: true },
  },
  {
    label: 'Start Of Haul Time',
    id: 'NetLeaveDepthDateTime',
    valid: valid.anyValue,
    type: 'datetime',
    default: null,
    copyFrom: 'RAEnd_date',
    display: { type: 'single' },
    optionalRender: true,
    realm: { type: 'date', optional: true },
  },
  {
    label: 'End Of Shot Location',
    id: 'NetAtDepthLocation',
    valid: valid.locationValid,
    type: 'location',
    default: null,
    copyFrom: 'locationStart',
    display: { type: 'single' },
    optionalRender: true,
    realm: { type: 'string', optional: true },
  },
  {
    label: 'End Of Shot Time',
    id: 'NetAtDepthDateTime',
    valid: valid.anyValue,
    type: 'datetime',
    default: null,
    copyFrom: 'RAStart_date',
    display: { type: 'single' },
    optionalRender: true,
    realm: { type: 'date', optional: true },
  },
  {
    label: 'Code End Time',
    id: 'codendDateTime',
    valid: valid.anyValue,
    type: 'datetime',
    default: null,
    copyFrom: 'RAEnd_date',
    displayStage: 'Haul',
    display: { type: 'single' },
    optionalRender: true,
    realm: { type: 'date', optional: true },
  },*/
  {
    label: 'Is Vessel Used',
    id: 'isNetLost',
    valid: valid.anyValue,
    type: 'bool',
    default: false,
    displayStage: 'Haul',
    display: { type: 'single' },
    realm: { type: 'bool' },
  },
  /*{
    label: 'Groundrope Depth',
    id: 'groundropeDepth',
    valid: valid.greaterThanZero,
    type: 'number',
    default: 0,
    combinedValid:
      {
        attributes: ["groundropeDepth", "bottomDepth"],
        func: combined.orderedLessThanOrEqual,
        errorMessage: "Groundrope cannot be below the bottom"
      },
    display: { type: 'child'}, unit: 'm', optionalRender: false,
    realm: { type: 'int', optional: true },
  },
  {
    label: 'Wing Spread',
    id: 'wingSpread',
    valid: valid.greaterThanZero,
    type: 'number',
    repeating: true,
    display: { type: 'combined', siblings: ['headlineHeight']}, unit: 'm', order: 1, optionalRender: true,
    realm: { type: 'int', optional: true },
  },
  {
    label: 'Headline Height',
    id: 'headlineHeight',
    valid: valid.greaterThanZero,
    type: 'float',
    unit: 'm',
    default: 0,
    optionalRender: true,
    repeating: true,
    display: { type: 'child'},
    realm: { type: 'float', optional: true },
  },
  {
    label: 'Average Speed',
    id: 'averageSpeed',
    valid: valid.greaterThanZero,
    type: 'float',
    default: 0,
    display: { type: 'single'},
    unit: 'kt',
    optionalRender: true,
    displayStage: 'Haul',
    realm: { type: 'float', optional: true },
  },*/
  {
    id: 'formType', default: 'TCER',
    realm: { type: 'string', default: 'TCER' },
  },
  /*{
    id: 'otherSpeciesWeight', default: 0,
    realm: { type: 'int', default: 0 },
  },*/
  {
    id: 'committed', default: false,
    realm: { type: 'bool', default: false, optional: true },
  }
];

export default TCERModel;
